version: 2.1

defaults: &defaults
  working_directory: ~/ring-okta
  docker:
    - image: clojure:lein-2.9.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}

      - run: lein deps

      - save_cache:
          key: v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}
          paths:
            - "~/.m2"

  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}

      - run: lein test-all-profiles

      - run: lein cloverage

  ancient:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-m2-{{ .Branch }}-{{ checksum "project.clj" }}

      - run: lein ancient :all

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - test:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - build

  monthly_deps_check:
    jobs:
      - ancient
    triggers:
      - schedule:
          # At 01:19 on day-of-month 20
          cron: "19 1 20 * *"
          filters:
            branches:
              only: master
