#! /bin/bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

# setup environment
export LEIN_ENV="test"

# run tests
echo "Running tests..."
date "+%H:%M:%S"

# run tests.
script/test
