name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # TODO: Cache deps
    - name: Install dependencies
      run: lein deps

  test:
    needs: build

    runs-on: ubuntu-latest

    # TODO: Restore deps

    steps:
    - name: Run tests
      run: lein test-all-profiles

    # TODO: Persist coverage reports
    - name: Run code coverage
      run: lein cloverage
