name: Build and Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache maven dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-maven-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: lein deps

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache maven dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-maven-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test-all-profiles

    - name: Run code coverage
      run: lein cloverage

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: docs/coverage

