name: Weekly Deps Check

on:
  schedule:
    # At 01:19 on Tuesday
    - cron: "19 1 * * Tue"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache maven dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-maven-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: script/bootstrap

  ancient:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache maven dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-maven-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Check ancient deps
      run: lein ancient :all :exclude okta
